export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const FILTER_VIDEOGAMES_BY_GENRES = 'FILTER_VIDEOGAMES_BY_GENRES';
export const GET_GENRES = 'GET_GENRES';
export const FILTER_CREATED_OR_EXISTED = 'FILTER_CREATED_OR_EXISTED';
export const ORDER_BY_RATING = 'ORDER_BY_RATING';
export const  GET_NAME_VIDEOGAMES = 'GET_NAME_VIDEOGAMES';
